version: '3.7'

services:
  camunda:
    build: .
    environment:
      - TZ=GMT-3
      - PGTZ=GMT-3
      - DB_URL=jdbc:postgresql://postgres:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda1!
      - DB_DRIVER=org.postgresql.Driver
    ports:
      - 80:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_PASSWORD=camunda1!
      - POSTGRES_USER=camunda
      - TZ=GMT-3
      - PGTZ=GMT-3
    volumes:
      # - ./camunda.sql:/docker-entrypoint-initdb.d/camunda.sql 
      - db-data-postgres/:/var/lib/postgresql/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./api/docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=chart@example.local
      - PGADMIN_DEFAULT_PASSWORD=pgadmin2020
    ports:
      - "8881:80"
    depends_on:
      - postgres
    # Para ver como configurar o PgAdmin acesse https://linuxhint.com/postgresql_docker/

  # gateway:
  #   image: traefik:v2.2
  #   command: --providers.docker=true --accesslog=true --api.dashboard=true --api.insecure=true
  #   ports:
  #   - 810:80
  #   - 8180:8080
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db-data-postgres: